### ISSUE TITLE
Unable to access to response headers 

### ISSUE THREAD

**Issue by hippo-tech** [BlurredSoftware/BSWFoundation#28]
Hi all,

Due to the version 1 of your library is not compatible with Xcode 10, we are updating our project to use the last stable version of the library. 

During that migration we have identified several functionalities that we cannot use on the current version.

Due to our app needs, we need to read response status code and headers. It was possible through the DroskyResponse (which has been removed) on version 1, but it is not possible on the current version, because the new APIClient class does not return this information.

Is there any way to read and process response status codes and http headers on the current version?

Thanks a lot.

**Comment by piercifani** [comment]
HI @hippo-tech,

I’m aware of this limitation and I’m working towards fixing this regression. This [commit](
https://github.com/theleftbit/BSWFoundation/commit/ec8dc4db74bd68af43a45ed25dc5fbe34988f7b0) is a work in progress towards a better way to expose the HTTP headers of the response.

I’m confident this issue will be fixed next week.

**Comment by piercifani** [comment]
Please check https://github.com/theleftbit/BSWFoundation/pull/29 to see if it suits your needs

**Comment by hippo-tech** [comment]
Hello, 

This commit does not allow us to use the version. 

We are executing requests which do not return a decodable structure (for example, an image). We also need to manage 401 errors and response headers on a generic way, without returning the control to the Controller. Summarizing, we want to manage the HTTP Response before decoding the response data and return it to the caller.

Can you add a new function "performRequest" which returns the APIClient Response in order to manage it from our side? It was included on the version 1 and removed on the current version. Without this function, our project integration can be really expensive in terms of work.

Thanks a lot.

**Comment by piercifani** [comment]
Would something like this work for you?

```swift
extension APIClient {
    public func perform(_ endpoint: Endpoint) -> Task<APIClient.Response> {
        return createURLRequest(endpoint: endpoint)
            ≈> sendNetworkRequest
    }
}
```

**Comment by hippo-tech** [comment]
Hello,

Apparently yes.

Thanks

**Comment by piercifani** [comment]
There you go https://github.com/theleftbit/BSWFoundation/pull/31

Let me know if this works via the PR, so I can close it and create a release with it

**Comment by hippo-tech** [comment]
Can you also add the function which expects a URLRequest instead of an Endpoint, please? Something like this:

    public func performSimpleRequest(_ request: URLRequest) -> Task<APIClient.Response> {
        return sendNetworkRequest(request:request, fileURL: nil)
    }

**Comment by piercifani** [comment]
But in this case, why even bother with `APIClient` and not just use `URLSession` directly? in that case you're effectively not using any of the features of BSWFoundation

**Comment by hippo-tech** [comment]
Hi Pierluigi, 

You are completely right. In that case it is not necessary to use the APIClient, we have updated it

I have checked that #31 is OK for us, thanks. But testing it, I have detected that form url encoded requests are not working properly (the Content-type request is not populated). To execute those requests, I have updated the Router class (setting content-type header if the parameter encoding is .url). Is it due to an incompatibilty with Alamofire version (we are using 4.6.0) or due to a bug?

Thanks a lot.

**Comment by piercifani** [comment]
We have removed Alamofire altogether from BSWFoundation. APIClient should be able to do everything it was perviously done by Drosky & Alamofire.

Would you mind opening an Issue with this ContentType thing (or even a PR if you can) so we can track this separately?

**Comment by hippo-tech** [comment]
Hi Pierluigi,

We have create the PR #32.

We will wait to you to upload it to a new version.

Thanks a lot.

**Comment by piercifani** [comment]
No @hippo-tech, thank you! https://github.com/theleftbit/BSWFoundation/pull/33

**Comment by piercifani** [comment]
Please find version 2.2.1 with the changes you requested!

```--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  BSWFoundation (2.2.1) successfully published
 📅  October 19th, 12:19
 🌎  https://cocoapods.org/pods/BSWFoundation
 👍  Tell your friends!
--------------------------------------------------------------------------------```
